# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  #vmImage: 'Ubuntu-16.04'
  vmImage: 'windows-2019'
variables:
  buildConfiguration: 'Release'
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.100'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'becauseimclever'
    scannerMode: 'MSBuild'
    projectKey: 'Fortinbra_HomeAutomation'
    projectName: 'HomeAutomation'
- script: dotnet restore

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildconfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Tests/*/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
    testRunTitle: 'Unit Tests'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'