# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  #vmImage: 'Ubuntu-16.04'
  vmImage: 'windows-2019'
variables:
  buildConfiguration: 'Release'
steps:
- task: DotNetCoreInstaller@0
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview9-014004'

- script: dotnet restore

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildconfiguration)'

- script: dotnet test AutomationUnitTests/AutomationUnitTests.csproj --logger trx --settings test.runsettings --collect "Code Coverage"
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'